name: Build

on:
  push:
    branches:
    - main


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '1.24.1' 

      - name: test
        run: go test ./...

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '1.24.1' 

      - name: build cmd
        run: go build cmd/dockerfile-parser/dockerfile-parser.go

